spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:http://devgrr:qwer1234@localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test-service
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/api/tests/**