server:
  port: 8000

spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    config:
      enabled: false  # Config Server 비활성화
#      import: optional:configserver:http://devgrr:qwer1234@localhost:8888
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:8000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
            allow-credentials: true
      routes:
        - id: test-service
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/api/tests/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
