server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: test-service
  profiles:
    active: dev
#  config:
#    import: optional:configserver:http://devgrr:qwer1234@localhost:8888
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # OpenFeign 설정
  cloud:
    config:
      enabled: false  # Config Server 비활성화
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: FULL
          user-service:
            connectTimeout: 3000
            readTimeout: 3000
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
      micrometer:
        enabled: true
      lazy-attributes-resolution: false

# Feign 로깅 설정
logging:
  level:
    com.interplug.testservice.client: DEBUG

# Circuit Breaker 설정 (Resilience4j)
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        slidingWindowSize: 10
  timelimiter:
    instances:
      user-service:
        timeoutDuration: 3s

# Swagger UI 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: true
