server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: test-service
  profiles:
    active: dev
#  config:
#    import: optional:configserver:http://devgrr:qwer1234@localhost:8888

  # R2DBC 설정 (WebFlux용)
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  # SQL 스키마 초기화
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  # Cloud Config 설정
  cloud:
    config:
      enabled: false  # Config Server 비활성화

# WebClient 로깅 설정
logging:
  level:
    com.interplug.testservice.client: DEBUG
    org.springframework.r2dbc: DEBUG

# Circuit Breaker 설정 (Resilience4j)
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        slidingWindowSize: 10
  timelimiter:
    instances:
      user-service:
        timeoutDuration: 3s

# Swagger UI 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: true
